include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    file_names: false

    avoid_relative_lib_imports: true
    always_use_package_imports: true

    library_private_types_in_public_api: false
    constant_identifier_names: true

    prefer_null_aware_operators: true

    cancel_subscriptions: true
    collection_methods_unrelated_type: true
    unnecessary_statements: true

    # Style Rules
    always_declare_return_types: true
    avoid_escaping_inner_quotes: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    directives_ordering: true
    # flutter_style_todos: true
    leading_newlines_in_multiline_strings: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_double_quotes: true
    # prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    # public_member_api_docs: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true

    # Pub Rules
    secure_pubspec_urls: true
